### ISSUE TITLE
Missing model & designer plugins

### ISSUE THREAD

**Issue by sjsf** [eclipse/smarthome-designer#2]
When trying to build the designer with an empty repository, it cannot resolve the model.ui and designer bundles:

```
Plug-in reference 'org.eclipse.smarthome.designer.core' cannot be resolved
Plug-in reference 'org.eclipse.smarthome.designer.ui' cannot be resolved
Plug-in reference 'org.eclipse.smarthome.model.item.ui' cannot be resolved
Plug-in reference 'org.eclipse.smarthome.model.persistence.ui' cannot be resolved
Plug-in reference 'org.eclipse.smarthome.model.rule.ui' cannot be resolved
Plug-in reference 'org.eclipse.smarthome.model.script.ui' cannot be resolved
Plug-in reference 'org.eclipse.smarthome.model.sitemap.ui' cannot be resolved
Plug-in reference 'org.eclipse.smarthome.model.thing.ui' cannot be resolved
```

In https://github.com/eclipse/smarthome-designer/pull/1#issuecomment-275740157 it was discussed to create a feature containing this stuff. However, I can't seem to find this in the eclipse/smarthome repo. Is that still the plan? Or what is the idea?

**Comment by maggu2810** [comment]
The bundles should be resolved by the remote location. See here:
https://github.com/eclipse/smarthome-designer/blob/master/targetplatform/smarthome-designer.target#L163-L169

IIRC If the latest "nightly" build on the HIPP failed, the remote repository could be empty (we should check the job configuration, but IIRC the repostiory is cleaned up in front of the build).

**Comment by sjsf** [comment]
> The bundles should be resolved by the remote location. See here:
https://github.com/eclipse/smarthome-designer/blob/master/targetplatform/smarthome-designer.target#L163-L169

Sure, the target platform points to the 
[org.eclipse.smarthome.feature.runtime.core](https://github.com/eclipse/smarthome/blob/master/features/org.eclipse.smarthome.feature.runtime.core/feature.xml) and [org.eclipse.smarthome.feature.runtime.model](https://github.com/eclipse/smarthome/blob/master/features/org.eclipse.smarthome.feature.runtime.model/feature.xml) features. I have seen that and my target platform resolves nicely. 

However, my point is that the above mentioned bundles are _not_ included in _any_ of these features. In essence we are missing a "designer" feature in [eclipse/smarthome](https://github.com/eclipse/smarthome) which includes the missing, designer-only bundles.

**Comment by maggu2810** [comment]
My last observation has been that files in sub-directories of model.xxx.ui are created by the build process of model.xxx (don't know the exact bundle that brings the files into).
So moving the ui bundles to another place is not possible.
I don't think it is a good approach to generate files of another bundle in the build process of a bundle...
But I was told that is the way of Xtext...
So I stopped the work on moving the model.xxx.ui bundles to this repository at all.

**Comment by sjsf** [comment]
> But I was told that is the way of Xtext...

Yes, this is how it is. All bundles related to one DSL somehow belong together, in Xtext's world...

Therefore I agree, we cannot move them over. Still, we need a feature in eclipse/smarthome which exposes the model.xxx.ui bundles.

**Comment by sjsf** [comment]
due to the discontinuation of the designer, this won't be fixed anymore.
